name: portscanner
version: 0.0.1
author: Ben Vinegar <ben@benv.ca>
description: A simple port scanner written in Dart.
homepage: http://github.com/benvinegar/dart-portscanner
dependencies:
  args: '>=0.12.2+1 <0.13.0'
  unittest: '>=0.11.4 <0.12.0'
